#!/bin/sh

# Enforce Conventional Commit Messages
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "❌ Aborting commit. Your commit message is invalid."
    echo "✅ Format: <type>(<scope>): <message>"
    echo "✅ Example: feat(auth): add login functionality"
    exit 1
fi
# Enforce Commit Message Length (Max 88 characters)
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "❌ Aborting commit. Your commit message is too long (max 88 characters)."
    exit 1
fi